name: Gentsshop CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  fe:
    name: Frontend CI
    runs-on: ubuntu-latest
    if: >
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'master' &&
      startsWith(github.event.pull_request.head.ref, 'feature')

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Application
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t gentsshop-frontend:latest -f Dockerfile.Frontend.v2 .
          docker tag gentsshop-frontend:latest gentsshop-frontend:${{ github.sha }}

      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/gentsshop-frontend:latest
          docker push $DOCKER_USERNAME/gentsshop-frontend:${{ github.sha }}

  be:
    name: Backend CI
    runs-on: ubuntu-latest
    if: >
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'master' &&
      startsWith(github.event.pull_request.head.ref, 'feature')

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t gentsshop-backend:latest -f Dockerfile .
          docker tag gentsshop-backend:latest gentsshop-backend:${{ github.sha }}

      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/gentsshop-backend:latest
          docker push $DOCKER_USERNAME/gentsshop-backend:${{ github.sha }}